import { Table } from 'react-bootstrap';

function TopPlayers() {
  return (
    <>
      <h3>Online Players</h3>
      <Table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Class</th>
            <th>Level</th>
            <th>Experience</th>
            <th>Gender</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Aragorn</td>
            <td>Warrior</td>
            <td>45</td>
            <td>12345</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Legolas</td>
            <td>Archer</td>
            <td>50</td>
            <td>14567</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Gimli</td>
            <td>Warrior</td>
            <td>40</td>
            <td>11000</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Gandalf</td>
            <td>Wizard</td>
            <td>60</td>
            <td>20000</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Frodo</td>
            <td>Rogue</td>
            <td>35</td>
            <td>9000</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Samwise</td>
            <td>Warrior</td>
            <td>34</td>
            <td>8700</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Arwen</td>
            <td>Mage</td>
            <td>45</td>
            <td>12000</td>
            <td>Female</td>
          </tr>
          <tr>
            <td>Eowyn</td>
            <td>Warrior</td>
            <td>42</td>
            <td>11500</td>
            <td>Female</td>
          </tr>
          <tr>
            <td>Elrond</td>
            <td>Mage</td>
            <td>55</td>
            <td>18000</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Galadriel</td>
            <td>Mage</td>
            <td>58</td>
            <td>19000</td>
            <td>Female</td>
          </tr>
          <tr>
            <td>Saruman</td>
            <td>Wizard</td>
            <td>60</td>
            <td>21000</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Boromir</td>
            <td>Warrior</td>
            <td>44</td>
            <td>11700</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Pippin</td>
            <td>Rogue</td>
            <td>33</td>
            <td>8500</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Merry</td>
            <td>Rogue</td>
            <td>33</td>
            <td>8400</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>Thranduil</td>
            <td>Archer</td>
            <td>52</td>
            <td>16000</td>
            <td>Male</td>
          </tr>
        </tbody>
      </Table>
    </>
  );
}

export default TopPlayers;
